### ISSUE TITLE
pose matching questions

### ISSUE THREAD

**Issue by faj2007** [flyawaychase/3DHumanPose#1]
How do you deal with the situations if some of the parts(like wise or ankle) is missing in the pose estimation? Because some of the parts like ankle are really important.

**Comment by flyawaychase** [comment]
We didn't explicitly handle the case where body parts are missing. Start from the 2D pose estimation, we assume all body parts are predicted. In the proposed approach, 3D pose is inferred purely from the 2D pose. We rely on the state-of-the-art 2D pose estimation to give all 2D body parts even when there are missing body parts in the image.

**Comment by faj2007** [comment]
it works somehow even some of the parts miss. thx
